# Generated by Django 4.2.2 on 2023-08-28 10:37

from django.db import migrations, models
import django.db.models.deletion
import reader.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("reader", "0001_create_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(max_length=100)),
            ],
            bases=(models.Model, reader.mixins.DateTimeMixin),
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="unique book number",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="book title")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="book.author"
                    ),
                ),
            ],
            bases=(models.Model, reader.mixins.DateTimeMixin),
        ),
        migrations.CreateModel(
            name="IssueBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_get", models.DateField(blank=True, null=True)),
                ("book_return", models.DateField(blank=True, null=True)),
                ("book", models.ManyToManyField(to="book.book")),
                ("reader", models.ManyToManyField(to="reader.reader")),
            ],
            bases=(models.Model, reader.mixins.DateTimeMixin),
        ),
        migrations.CreateModel(
            name="OnHandBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="book.book"
                    ),
                ),
                ("issuebook", models.ManyToManyField(to="book.issuebook")),
                (
                    "reader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="reader.reader"
                    ),
                ),
            ],
            bases=(models.Model, reader.mixins.DateTimeMixin),
        ),
    ]
