# Generated by Django 4.2.2 on 2023-08-28 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_create_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issuebook",
            name="book",
        ),
        migrations.RemoveField(
            model_name="issuebook",
            name="reader",
        ),
        migrations.RemoveField(
            model_name="onhandbook",
            name="issuebook",
        ),
        migrations.AddField(
            model_name="issuebook",
            name="on_hand_book",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="book.onhandbook",
            ),
        ),
    ]
