# Generated by Django 4.2.4 on 2023-08-25 08:40

import django.db.models.deletion
import reader.mixins
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_create_author_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_number",
                    models.CharField(max_length=250, verbose_name="unique book number"),
                ),
                ("name", models.CharField(max_length=250, verbose_name="book title")),
                (
                    "author",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="book.author"),
                ),
            ],
            bases=(models.Model, reader.mixins.DateTimeMixin),
        ),
    ]
