# Generated by Django 4.2.4 on 2023-08-25 08:49

import django.db.models.deletion
import reader.mixins
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reader", "0004_create_author_model"),
        ("book", "0002_create_book_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_get", models.DateField(auto_now_add=True)),
                ("book_return", models.DateField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="book.book"),
                ),
                (
                    "reader",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reader.reader",
                    ),
                ),
            ],
            bases=(models.Model, reader.mixins.DateTimeMixin),
        ),
    ]
