# Generated by Django 4.2.2 on 2023-08-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_change_onhandbook_issuebook_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuebook",
            name="book_get",
            field=models.DateField(auto_now_add=True, help_text="гг-мм-дд"),
        ),
    ]
