# Generated by Django 4.2.4 on 2023-08-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0003_create_issuebook_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuebook",
            name="book_get",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="issuebook",
            name="book_return",
            field=models.DateField(blank=True, null=True),
        ),
    ]
