# Generated by Django 4.2.2 on 2023-08-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0003_change_issuebook_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuebook",
            name="book_get",
            field=models.DateField(
                blank=True, help_text="гг-мм-дд", null=True, verbose_name="Введите дату"
            ),
        ),
    ]
