# Generated by Django 4.2.4 on 2023-08-27 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reader", "0004_create_author_model"),
        ("book", "0004_update_issuebook_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="unique_number",
            field=models.CharField(max_length=250, unique=True, verbose_name="unique book number"),
        ),
        migrations.AlterField(
            model_name="issuebook",
            name="reader",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="reader.reader"),
        ),
    ]
