# Generated by Django 4.2.2 on 2023-08-29 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0004_change_issuebook_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuebook",
            name="book",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="book.book"
            ),
        ),
        migrations.AlterField(
            model_name="issuebook",
            name="book_get",
            field=models.DateField(
                blank=True,
                help_text="в формате: год-месяц-день",
                null=True,
                verbose_name="Введите дату",
            ),
        ),
    ]
