# Generated by Django 4.2.4 on 2023-08-27 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reader", "0004_create_author_model"),
        ("book", "0005_change_issuebook_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuebook",
            name="book",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="book.book"),
        ),
        migrations.AlterField(
            model_name="issuebook",
            name="reader",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reader.reader",
            ),
        ),
    ]
