# Generated by Django 4.2.2 on 2023-08-29 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0006_change_issuebook_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issuebook",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="book.book"
            ),
        ),
        migrations.AlterField(
            model_name="issuebook",
            name="on_hand_book",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="book.onhandbook",
            ),
        ),
    ]
