# Generated by Django 4.2.2 on 2023-08-30 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reader", "0001_create_models"),
        ("book", "0009_change_onhandbook_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issuebook",
            name="on_hand_book",
        ),
        migrations.AddField(
            model_name="book",
            name="available",
            field=models.BooleanField(default=True, verbose_name="Книга доступна?"),
        ),
        migrations.AddField(
            model_name="issuebook",
            name="reader",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="reader.reader",
            ),
        ),
    ]
