# Generated by Django 4.2.2 on 2023-08-31 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reader", "0001_create_models"),
        ("book", "0010_change_book_issuebook_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="onhandbook",
            name="issuebook",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="book.issuebook",
            ),
        ),
        migrations.AlterField(
            model_name="issuebook",
            name="reader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="reader.reader"
            ),
        ),
    ]
