# Generated by Django 4.2.2 on 2023-08-28 10:37

from django.db import migrations, models
import reader.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_name_id",
                    models.CharField(
                        max_length=150,
                        unique=True,
                        verbose_name="Фамилия-уникальный номер читателя",
                    ),
                ),
                ("first_name", models.CharField(max_length=150, verbose_name="Имя")),
                (
                    "middle_name",
                    models.CharField(max_length=150, verbose_name="Отчество"),
                ),
            ],
            bases=(models.Model, reader.mixins.DateTimeMixin),
        ),
    ]
