# Generated by Django 4.2.4 on 2023-08-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reader", "0002_create_reader_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.AddField(
            model_name="user",
            name="last_name_number",
            field=models.CharField(
                default=0,
                max_length=250,
                unique=True,
                verbose_name="last name - unique number",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="middle_name",
            field=models.CharField(max_length=150, verbose_name="middle name"),
        ),
    ]
